name: example_ci

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: test CI
        run: |
          echo "Hello there!"
          echo "I hope you are having a great day!"
          echo "This is a test CI job."
          echo "this shouldnt work
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: compile and run
        run: |
          echo $(pwd)
          mkdir build
          mkdir run
          cd build
          cmake ../
          cmake --build .
          cd ../run
          ./greetings