name: example_ci

on: push

jobs:
  hello-message:
    runs-on: ubuntu-latest
    steps:
      - name: test CI
        run: |
          echo "Hello there!"
          echo "I hope you are having a great day!"
          echo "This is a test CI job."
  compile-and-run-greetings:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up CMake
      uses: lukka/get-cmake@latest
    - name: compile greetings
      run: |
          mkdir build
          mkdir run
          cd build
          cmake ../
          cmake --build .
    - name: run greetings
      run: |
          cd run
          ./greetings
  compile-and-run-greetings-windows:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up CMake
      uses: lukka/get-cmake@latest
    - name: compile greetings
      run: |
          mkdir build
          mkdir run
          cd build
          cmake ../
          cmake --build . --config Release
    - name: run greetings
      run: |
          cd run
          greetings.exe
