name: example_ci

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: test CI
        run: |
          echo "Hello there!"
          echo "I hope you are having a great day!"
          echo "This is a test CI job."
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checkout code
        uses: actions/checkout@v4   
       
       -name: Cmake roject
        run: |
          mkdir build_greetings
          cd build_greetings
          cmake ../greetings
          cmake --build .s